version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_contabil
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_cont
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d